apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: last-hope
        image: anishabhatnagar/last-hope:latest
        ports:
        - containerPort: 7860
        resources:
          limits:
            nvidia.com/gpu: 1  # Requesting 1 GPU
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
